
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mad-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mad-controller
  template:
    metadata:
      labels:
        app: mad-controller
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      securityContext: {}
      serviceAccountName: mad-controller
      automountServiceAccountToken: true
      containers:
      - name: mad-controller
        image: "mad:0.0.1"
        imagePullPolicy: Never
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
