//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Kubernetes mad Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthcheckRecord) DeepCopyInto(out *HealthcheckRecord) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
	if in.Healthy != nil {
		in, out := &in.Healthy, &out.Healthy
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthcheckRecord.
func (in *HealthcheckRecord) DeepCopy() *HealthcheckRecord {
	if in == nil {
		return nil
	}
	out := new(HealthcheckRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsAnomalyDetectorResource) DeepCopyInto(out *MetricsAnomalyDetectorResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsAnomalyDetectorResource.
func (in *MetricsAnomalyDetectorResource) DeepCopy() *MetricsAnomalyDetectorResource {
	if in == nil {
		return nil
	}
	out := new(MetricsAnomalyDetectorResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricsAnomalyDetectorResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsAnomalyDetectorResourceList) DeepCopyInto(out *MetricsAnomalyDetectorResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetricsAnomalyDetectorResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsAnomalyDetectorResourceList.
func (in *MetricsAnomalyDetectorResourceList) DeepCopy() *MetricsAnomalyDetectorResourceList {
	if in == nil {
		return nil
	}
	out := new(MetricsAnomalyDetectorResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricsAnomalyDetectorResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsAnomalyDetectorResourceSpec) DeepCopyInto(out *MetricsAnomalyDetectorResourceSpec) {
	*out = *in
	if in.HealthcheckEndpoints != nil {
		in, out := &in.HealthcheckEndpoints, &out.HealthcheckEndpoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsAnomalyDetectorResourceSpec.
func (in *MetricsAnomalyDetectorResourceSpec) DeepCopy() *MetricsAnomalyDetectorResourceSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsAnomalyDetectorResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsAnomalyDetectorResourceStatus) DeepCopyInto(out *MetricsAnomalyDetectorResourceStatus) {
	*out = *in
	in.LastBufferModificationTime.DeepCopyInto(&out.LastBufferModificationTime)
	if in.LastBuffer != nil {
		in, out := &in.LastBuffer, &out.LastBuffer
		*out = make([]HealthcheckRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HealthcheckEndpointsHealthy != nil {
		in, out := &in.HealthcheckEndpointsHealthy, &out.HealthcheckEndpointsHealthy
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.LastHealthcheckQueryTime.DeepCopyInto(&out.LastHealthcheckQueryTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsAnomalyDetectorResourceStatus.
func (in *MetricsAnomalyDetectorResourceStatus) DeepCopy() *MetricsAnomalyDetectorResourceStatus {
	if in == nil {
		return nil
	}
	out := new(MetricsAnomalyDetectorResourceStatus)
	in.DeepCopyInto(out)
	return out
}
